[bumpversion]
current_version = 0.0.4

[bumpversion:file:Cargo.toml]
search = version = "{current_version}"
replace = version = "{new_version}"

[bumpversion:file:README.md]
search = crc32-v2 = "{current_version}"
replace = crc32-v2 = "{new_version}"
