[package]
name = "crc32-v2"
version = "0.2.0"
edition = "2024"
authors = ["Mahmoud Harmouch <oss@wiseai.dev>", "Arlie Davis <arlie.davis@gmail.com>"]
description = "A port of the CRC-32 algorithm from zlib to Rust."
license = "MIT"
homepage = "https://github.com/wiseaidev/crc32-v2"
documentation = "https://docs.rs/crc32-v2"
repository = "https://github.com/wiseaidev/crc32-v2"
keywords = ["crc32", "checksum", "hash", "zlib", "no_std"]
categories = ["algorithms", "encoding", "no-std"]
build = "build.rs"
exclude = [
    "/tests",
    ".*",
    "/python",
    "/assets",
    "/benches",
    "/benchmarks",
    "NODE.md",
    "PYTHON.md",
    "RUST.md",
    "PACKAGING.md",
    "package.json",
    "package-lock.json",
    "pyproject.toml",
    "CONTRIBUTING.md",
]

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
pyo3 = { version = "0.29.2", features = ["extension-module"], optional = true }
napi = { version = "3.12.2", default-features = false, features = ["napi4"], optional = true }
napi-derive = { version = "3.6.3", optional = true }

[build-dependencies]
crc32-codegen = { version = "0.1.0", path = "crc32-codegen" }
napi-build = { version = "2.4.1", optional = true }

[dev-dependencies]
crc32fast = "1.5.1"
crc = "3.4.0"
zlib-rs = "0.6.7"
criterion = { version = "0.8.2", features = ["html_reports"] }
bump2version = "0.2.2"

[[bench]]
name = "benchmark"
harness = false

[[bench]]
name = "nano_benchmark"
harness = false

[[bench]]
name = "compare_benchmark"
harness = false

[features]
default = ["std"]
std = []
python = ["pyo3", "std"]
node = ["napi", "napi-derive", "napi-build", "std"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3

debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
incremental = false
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
incremental = false
overflow-checks = false

[badges]
maintenance = { status = "actively-developed" }
